// JS that displays a random joke every time the site is loaded.

jokes = ["My uncle named his dogs 'Timex' and 'Rolex'. They're his watch dogs.",
  "Did you hear about the guy whose left side was cut off? He's all right now.",
  "How do you open a banana? With a mon-key.",
  "Which is faster, hot or cold? Hot, because you can catch cold.",
  "What did one plate say to the other plate? Dinner's on me.",
  "Where does Batman go to the bathroom? The batroom.",
  "What did the left eye say to the right eye? Between you and me, something smells.",
  "What do you call a fake noodle? An 'impasta'.",
  "I'm so good at sleeping that I can do it with my eyes closed!",
  "What happens when a 'strawberry' gets run over crossing the street? Traffic 'jam'.",
  `A termite walks into a bar and says, "So, is the bar 'tender' here?"`,
  "How does an octopus go into battle? Well-armed.",
  "How do celebrities stay cool? They have many fans.",
  "Where do young trees go to learn? Elementree school.",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "How did the student feel when he learned about electricity? Totally shocked.",
  "What do you call a bee that can't make up its mind? A Maybe.",
  "What did one wall say to the other? I'll meet you at the corner.",
  "Why couldn't the bicycle stand up by itself? It was two 'tired'.",
  "Why did the student eat his homework? Because his teacher told him it was a piece of cake.",
  "What did the full glass say to the empty glass? You look drunk.",
  "What's the best smelling insect? A deodor-ant.",
  "What musical instrument is found in the bathroom? A tuba toothpaste.",
  "Why did the kid bring a ladder to school? Because she wanted to go to high school.",
  "How does a scientist freshen his/her breath? With experi-mints.",
  "What building in your town has the most stories? The public library.",
  "What is a computer's favorite snack? Computer chips.",
  "What did one volcano say to the other? I lava you.",
  "How do we know that the ocean is friendly? It waves.",
  "What falls in winter but never gets hurt? Snow.",
  "What did the little corn say to the mama corn? Where is 'pop' corn?",
  "What kind of tree fits in your hand? A palm tree.",
  "Why is the obtuse triangle always so frustrated? Because it’s never right.",
  "Why is six afraid of seven? Because seven eight nine.",
  "Why was the math book sad? Because it had too many problems.",
  "What do dentists call their x-rays? Tooth pics!",
  "How do you measure a snake? In inches—they don’t have feet.",
  "Why did the bullet end up losing its job? It got fired.",
  "What does a house wear? An AdDRESS!",
  `Two windmills are standing on a wind farm. One asks, "What’s your favorite kind of music?" The other replies, "I’m a big metal fan."`,
  "How does NASA organize a party? They planet.",
  "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
  "What gets wetter the more it dries? A towel.",
  "Where should you go in the room if you’re feeling cold? The corner—they’re usually 90 degrees.",
  "What do you call malware on a Kindle? A bookworm.",
  "Did you hear about the painter who was hospitalized?<br>The doctors say it was due to too many 'strokes'.",
  `What did the tie say to the hat?<br>"You go on a'head'. I’ll hang around."`,
  "What kind of shoes does a spy wear? Sneakers.",
  "Why are frogs always so happy? They eat whatever bugs them.",
  "Why didn’t the skeleton go to the dance? Because it had 'no body' to go with.",
  "What do you call a musician with problems? A trebled man.",
  "Where do snowmen keep their savings? In the snowbank.",
  "What did one elevator say to the other? I think I’m 'coming up' with something.",
  "What do you call a belt with a watch on it? A waist of time.",
  "Why won’t skeletons fight each other? They just don’t have the guts.",
  "Never trust atoms, they make up everything.",
  "The future, the present, and the past walk into a bar. Things got a little tense-d.",
  "She got a new pair of gloves today, but they’re both ‘lefts’, which on the one hand is great, but on the other, it’s just not right.",
  "What’s a frog’s favorite type of shoes? Open toad sandals.",
  "What’s the difference between ignorance and apathy? I don’t know and I don’t care.",
  "What do Alexander the Great and Winnie-the-Pooh have in common? Same middle name.",
  "Which branch of the military accepts toddlers? The infantry.",
  "Though he enjoys tennis a lot, he could never date a tennis player. LOVE means nothing to tennis players.",
  "A foke went bald years ago, but still carries around an old comb. He just can't part with it.",
  "Did you hear how the zombie bodybuilder hurt his back? He was dead-lifting.",
  "Never criticize someone until you have walked a mile in their shoes. That way, when you criticize them, you'll be a mile away, and you'll have their shoes.",
  "What do you call it when Batman skips church? Christian Bale.",
  "What's a foot long and slippery? A slipper.",
  "Where does the General keep his armies? In his sleevies.",
  "What is the biggest lie in the entire universe?<br>I have read and agree to the Terms & Conditions.",
  "What is an astronaut’s favorite key on a keyboard? The space bar.",
  "Debugging is like being the detective in a crime movie where you’re also the murderer.",
  "What do you call a computer mouse that swears a lot? A cursor!",
  `I tried to say, "I'm a functional adult", but my phone autocorrected it to "fictional adult", and I feel like that's more accurate.`,
  "If 'apple' made a car, would it have 'windows'?",
  "Why do Java developers wear glasses? Because they can’t C#.",
  "Where did the software developer go?! I don’t know, he ran-som-ware!",
  `I changed my password to "incorrect". So whenever I forget what it is, the computer will say "Your password is incorrect."`,
  "Do you know the keyboard shortcut to help you not have to go the bathroom when you’re working or playing PC games? Ctrl P.",
  "Why was the JavaScript developer sad? Because she didn’t NODE how to EXPRESS herself."
];


let rand_joke_num = Math.trunc(Math.random() * (jokes.length - 0) + 0);

document.getElementsByTagName("p")[0].innerHTML = jokes[rand_joke_num];